### ISSUE TITLE
Move tests from Jasmine to Jest

### ISSUE THREAD

**Issue by stremlenye** [stremlenye/rlux-mod#1]
Encountered a lot of problems while covering flux parts with Jasmine tests, such as Promises hack with done function. Also I gave up after realised that Jasmine seems can't work with Dispatcher.

Found Jest framework, which was built by Facebook team. Decided to try it out.

**Comment by emmenko** [comment]
Yes, `Jest` is the recommended tool for testing (which is built on top of `Jasmine`). 
Here a couple of interesting links:
- https://reactjsnews.com/building-a-test-suite-in-react-js/
- http://facebook.github.io/react/blog/2014/09/24/testing-flux-applications.html

**Comment by stremlenye** [comment]
Thank you for links. Already tried some cases.
Jasmine legacy is either good and bad: it wasn't hard to move existing test to Jest, but also in has same problem with async calls as Jasmine. But also it has a solution: `it` -> `pit` and return Promises/A+. Seems works fine.
